- name: Add Spotify Repo
  apt_repository:
    repo: deb http://repository.spotify.com stable non-free
    state: present
    filename: /etc/apt/sources.list.d/spotify

- name: Add Spotify key
  apt_key:
    keyserver: "hkp://keyserver.ubuntu.com:80"
    id: "{{ item }}"
    #    id: BBEBDCB318AD50EC6865090613B00F1FD2C19886
    state: present
  with_items:
   - "0DF731E45CE24F27EEEB1450EFDC8610341D9410"
   - "931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90"


- name: install Spotify
  apt:
    name={{ item }}
    update_cache=yes
    force=yes
  with_items:
    - spotify-client
