- name: get Atom DEB
  get_url:
    url=http://atom.io/download/deb
    dest=/tmp/atom.deb
    mode=0755

- name: install Atom
  apt:
    deb=/tmp/atom.deb

- name: install Atom's packages
  command: "apm install linter linter-flake8 language-docker linter-docker markdown-preview-plus pretty-json"
  become: false
