- name: install Apps
  apt:
    name={{ item }}
    update_cache=yes
  with_items:
#    - midori
#    - midori-dbg
#    - icedtea-8-plugin
#    - icedtea-plugin
#    - libstdc++5:i386
#    - libpam0g:i386
#    - libx11-6:i386
    - terminator
    - python-setuptools
    - python3-setuptools
    - git
    - vim
#    - shutter
    - libxml2-utils
#    - corebird
    - jq
    - curl
    - ssh
    - redis-tools
    - awscli
    - ca-certificates
    - apt-transport-https
    - software-properties-common
    - htop
    - sysstat
    - meld
    - wget

- name: install PIP
  easy_install:
    name=pip

- name: install PIP3
  easy_install:
    name=pip
    executable=easy_install3

- name: install PIP apps
  pip:
    name={{ item }}
  with_items:
    - awscli
    - boto
    - boto3
    - elasticsearch
    - docker
    - docker-compose
    - requests
    - redis
    - pymongo

- name: install PIP3 apps
  pip:
    name={{ item }}
    executable=pip3
  with_items:
    - awscli
    - boto
    - boto3
    - elasticsearch
    - docker
    - docker-compose
    - requests
    - redis
    - pymongo
    - Flask
    - python-decouple
    - requests
    - jinja2
